import { Poppins } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from '@clerk/nextjs';
import ClientWrapper from './components/ClientWrapper'; // Import the client-side wrapper
import { auth } from '@clerk/nextjs/server';

const poppins = Poppins({ weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'], subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  // Fetch the userId server-side
  const { userId } = await auth();

  return (
    <ClerkProvider>
      <html lang="en">
        <body className={poppins.className}>
          <ClientWrapper userId={userId}>
            {children}
          </ClientWrapper>
        </body>
      </html>
    </ClerkProvider>
  );
}
