import { Poppins } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from '@clerk/nextjs';
import ClientWrapper from './components/ClientWrapper'; // Import the client-side wrapper
import { auth } from '@clerk/nextjs/server';
import BackToTopButton from './components/BackToTopButton'; 
import Head from 'next/head'; 

const poppins = Poppins({ weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'], subsets: ["latin"] });

export const metadata = {
  title: "Bagani Blades",
  description: "Generated by create next app",
  image: "/thumbnails/thumbnails.PNG" 
};

export default async function RootLayout({ children }) {
  // Fetch the userId server-side
  const { userId } = await auth();

  return (
    <ClerkProvider>
      <html lang="en">
        <Head>
          <meta property="og:image" content={metadata.image} />
          <meta name="twitter:image" content={metadata.image} />
          <meta name="description" content={metadata.description} />
          <meta property="og:title" content={metadata.title} />
          <meta property="og:description" content={metadata.description} />
          <meta property="og:image" content={metadata.image} />
        </Head>
        <body className={poppins.className}>
          <ClientWrapper userId={userId}>
            {children}
            <BackToTopButton />
          </ClientWrapper>
        </body>
      </html>
    </ClerkProvider>
  );
}
